Fe 3 add common pages
AntoninaKobzar/InternFront pull request #3
Opened 2023-11-02 08:30 UTC by AntoninaKobzar

pages added

2023-11-06 15:55 UTC, AntoninaKobzar commented
pages folder`s been removed

2023-11-07 09:25 UTC, alexskursky requested changes
1. Group your routes with `Route Groups`. Create groups for `auth` and `main app` (private and public routes).
https://nextjs.org/docs/app/building-your-application/routing/route-groups
2. Name your components files with a capital letter.
3. Group your routes like this - `users/[userId]`, `companies/[companyId]` etc.

2023-11-07 09:25 UTC, alexskursky commented on app/company_profile/page.tsx
This page should have dynamic path

2023-11-07 09:25 UTC, alexskursky commented on app/user_profile/page.tsx
This page should have dynamic path

2023-11-09 12:32 UTC, AntoninaKobzar commented
routes with Route Groups created for auth and main app (private and public routes).
components files named with a capital letter.
routes grouped :users/[userId], companies/[companyId] etc.

2023-11-10 11:02 UTC, alexskursky approved these changes

2023-11-10 11:02 UTC, merged